name: coin_identifier
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

